language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

deploy:
  # SNAPSHOTS from develop & jdk8
  - provider: script
    script: mvn deploy -Dmaven.test.skip -s .travis.settings.xml -P deploy-snapshots
    skip_cleanup: true
    on:
      branch: develop
      jdk: oraclejdk8
      condition: type != pull_request && fork = false
      
  # RELEASES from master & jdk8
  - provider: script
    script: mvn deploy -Dmaven.test.skip -s .travis.settings.xml -P deploy-releases
    skip_cleanup: true
    on:
      branch: master
      jdk: oraclejdk8
      condition: type != pull_request && fork = false
